server:
  port: 8008
spring:
  application:
    name: jwt-01
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/jwt_o1
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  security:
    user:
      password: Test12345_



